services:
  service-pg:
    image: bitnami/postgresql
    ports:
      - "5433:5432" # Porta pré-definida para o Postgres mas a 32 estava ocupada
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=connect

  service-redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
